import turtle
turtle.Screen().bgcolor("Orange")
board=turtle.Turtle()
board.forward(100)
board.right(90)
board.forward(100)
board.right(90)
board.forward(100)
board.right(90)
board.forward(100)
board.right(90)